#!/bin/bash
rm -rvf thumbnails/build
mkdir thumbnails/build
cd thumbnails/build
cp ../__init__.py __init__.py
cp ../shipshack.py shipshack.py
cp -rvf $VIRTUAL_ENV/lib/python2.7/site-packages/* .
zip -X -r shipshack.zip *
aws s3 cp shipshack.zip s3://shipshack/ --region=eu-central-1
aws lambda update-function-code --function-name=arn:aws:lambda:us-east-1:207553878010:function:shipshack --s3-bucket=shipshack --s3-key=shipshack.zip
